<h1>Podstawy Python jupyter 2</h1>
<p><h3>Poniżej znajdują się ćwiczenia pokazujące działanie Pythona oraz rozwiązane challenge z drugiej części podstaw</h3></p>

In [1]:
import numpy as np

In [12]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [13]:
a_list+b_list
n_array+n_array

array([ 2,  4,  6,  8, 10])

In [12]:
a_list[3]

NameError: name 'k_list' is not defined

In [15]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100, 100]


In [13]:
k_krotka[4]

5

In [14]:
k_krotka.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [8]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [9]:
n_array = np.array(a_list) # wektor numpy

In [10]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat'], dtype=object)

In [17]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [18]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [21]:
studenci_slownik["Zosia"]

22

In [19]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [23]:
for elementy in studenci_slownik.items():
    print(elementy)

('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])


In [24]:
for elementy in studenci_slownik.values():
    print(elementy)

3
5
22
[2, 21]


In [30]:
studenci_slownik["Cuthulu"]= -1000000

In [31]:
studenci_slownik

{'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], 'Cuthulu': -1000000}

In [20]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [36]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 'Igor', 1: 'Frankek', 2: 'Zosia', 3: 'Julia', 4: 'Cuthulu'}


In [22]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [23]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [24]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [25]:
1 in a
"Igor" in studenci_slownik

True

### Własne typy

In [107]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [26]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [28]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [32]:
pio_zajecia.ile_zajec

4

In [102]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [33]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [34]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [35]:
pio_zajecia.ile_mispow()

4

In [95]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [85]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [105]:
print(pio_zajecia.ile_zajec)

5


In [108]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [109]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [112]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [113]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [114]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


<h2> Challenge 1: </h2>
<p>Zadanie:</p>
<p>Stworzyc typ Numer Telefonu</p>
<ul>
<li>przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error</li>
<li>gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"</li>
<li>gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy</li>
</ul>
<p><p>Odpowiada on na nastepujące rzeczy</p></p>
<ul>
<li>numer_lodz = NumerTelefonu("426877868")</li>
>>"prawidlowy numer"
<li>numer_lodz.wojewodztwo</li>
>>"Lodz"
<li>print(numer_lodz)</li>
>>"cztery dwa sześć osiem siedem siedem osiem sześć osiem"
</ul>
 
<p>Pierwsza funkcja służy do sprawdzanie długości numeru telefony.Jeśli posiada on 9 liczb to wyświetli nam że podany numer jest prawidłowy natomiast gdy nie zostanie spełniony ten warunek to funkcja wyprintuje nam ERROR</p>
<p></p>
<p>Druga funkcja sprawdza nam z jakiego województwa jest dany numer.Porównuje ona pierwszą i drugą cyfre numeru i jesli zgadza sie ona z zadeklarowanymi przeznas wypisuje nazwe województwa, natomiast jesli sie nie zgadza wypisuje że podany numer należy do telefonu komórkowego.Zostały podane przykładowe województwa jednak nie jest to idealne przedstawienie województw ponieważ numery te są zależne od większykszych miast znajdujących się w nich co nawiązuje do starego podziału kraju na województwa.</p>
<p></p>
<p>Ostatnia funkcja analizuje każdą cyfre zapisaną w numerze tlefonu i podrzedstawia jej słowyny odpowiednik typu string.Następnie przekształca liste w numer zapisany słownie w postaci stringa</p>

In [34]:

class NumerTelefonu():
 
    def __init__(self, numer):
        if len(numer) == 9:
            print("Prawidlowy numer")
        else:
            print("ERROR")
        self.numer = numer
 
    @property
    def wojewodztwo(self):
        if self.numer[0] == "4" and self.numer[1] == "2":
            print("Łodzkie")
        elif self.numer[0] == "1" and self.numer[1] == "2":
            print("Małopolskie")
        elif self.numer[0] == "4" and self.numer[1] == "8":
            print("Mazowieckie")
        elif self.numer[0] == "9" and self.numer[1] == "1":
            print("Zachodnio-Pomorskie")
        else:
            print("Telefon komorkowy")
 
    def __repr__(self):
        numerek = ""
        for i in range(len(self.numer)):
            if self.numer[i] == "0":
                numerek += "Zero "
            elif self.numer[i] == "1":
                numerek += "Jeden "
            elif self.numer[i] == "2":
                numerek += "Dwa "
            elif self.numer[i] == "3":
                numerek += "Trzy "
            elif self.numer[i] == "4":
                numerek += "Cztery "
            elif self.numer[i] == "5":
                numerek += "Pięć "
            elif self.numer[i] == "6":
                numerek += "Sześć "
            elif self.numer[i] == "7":
                numerek += "Siedem "
            elif self.numer[i] == "8":
                numerek += "Osiem "
            elif self.numer[i] == "9":
                numerek += "Dziewięć "
        return numerek
 

 
numer_lodz = NumerTelefonu("12687788")
numer_lodz.wojewodztwo
print(numer_lodz)
    

ERROR
Małopolskie
Jeden Dwa Sześć Osiem Siedem Siedem Osiem Osiem 


TypeError: NumerTelefonu() takes no arguments